### ISSUE TITLE
Removing remission?

### ISSUE THREAD

**Issue by jonbakerfish** [haomo-ai/MotionSeg3D#10]
Hi, have you tried removing remission from input for training and infering? Is there a huge impact for the model's performance?

**Comment by MaxChanger** [comment]
Thanks for your interest in our project.
Remission or intensity often retains input in some common point cloud segmentation or object detection network structures.
In this work, we also keep the intensity input for fair comparison with the baselines.
We didn't try to remove the intensity. But it is very simple to remove this item, you only need to modify the number of layers in the network and the corresponding data.

**Comment by MaxChanger** [comment]
Since there is no update. I would like to close this issue.

Feel free to reopen this issue if needed.
