### ISSUE TITLE
about evaluation

### ISSUE THREAD

**Issue by QYChan** [haomo-ai/MotionSeg3D#12]
Hi, I am trying to reproduce the result in your paper but can not understand the evaluation metric difference between training and evaluation script.
In training, I got 
![lI7rSYJ6GS](https://user-images.githubusercontent.com/98118816/208573122-c297f2b5-1438-4a3b-a91e-9135a66c938e.png)
But in evaluating, the result was
![FZ57xZitix](https://user-images.githubusercontent.com/98118816/208573380-050b75c7-9e89-4ba4-9104-321e05965739.png)
What's differences between two 'iou moving' values?
Thanks in advance!

**Comment by MaxChanger** [comment]
Hi @QYChan, thank you for your interest in our project.
A quick answer is that the range image is used during training (without using PointHead). In Salsanext backbone, loss and metrics are based on image-level.(I guess for faster training etc.) 
In the evaluation, it is consistent with the benchmark, and the metrics are calculated at the point-level. So there will be some difference between the two printed results.
