### ISSUE TITLE
questions about evaluation and learning map in label config

### ISSUE THREAD

**Issue by Terminal-K** [haomo-ai/MotionSeg3D#13]
Hi, I'm confused about the  learning_map in semantic-kitti-mos.yaml. Why 0 and 1 are mapped to "static", while them are mapped to "unlabeled" in LiDAR-MOS or 4DMOS project?
semantic-kitti-mos.yaml in this project:
https://github.com/haomo-ai/MotionSeg3D/blob/ce43ed4f4f8b693c01854be046b00eaf6ed88cf9/config/labels/semantic-kitti-mos.yaml#L122

semantic-kitti-mos.yaml in LiDAR-MOS project:
https://github.com/PRBonn/LiDAR-MOS/blob/4f2e96f46f5ac267cf00e404ec94514f91ebfbf1/mos_SalsaNext/train/tasks/semantic/config/labels/semantic-kitti-mos.yaml#L115

semantic-kitti-mos.yaml in 4DMOS project:
https://github.com/PRBonn/4DMOS/blob/bfffcbb53355fc2057358640a00f5c215390c0ae/config/semantic-kitti-mos.yaml#L116

Besides, I wonder if there is point loss in the process from range image to pointcloud? Because when I run infer.py, I find the moving iou is less than that got in training

**Comment by MaxChanger** [comment]
Sorry for the late reply, I just finished my vacation.
In labeling KITTI-Road, there is no good way to distinguish unlabeled and static points, so they are labeled in the same category. 
And in LiDAR-MOS and 4DMOS, the unlabeled category does not supervise.
https://github.com/PRBonn/4DMOS/blob/bfffcbb53355fc2057358640a00f5c215390c0ae/src/mos4d/models/loss.py#L12-L36
https://github.com/PRBonn/4DMOS/blob/bfffcbb53355fc2057358640a00f5c215390c0ae/config/semantic-kitti-mos.yaml#L157-L160
```shell
learning_ignore: # Ignore classes
  0: True      # "unlabeled", and others ignored
  1: False     # "static"
  2: False     # "moving"
```

**Comment by MaxChanger** [comment]
For the second question, refer to https://github.com/haomo-ai/MotionSeg3D/issues/12.
Same with LMNet and SalsaNext, in Salsanext backbone, loss and metrics are based on image-level.(I guess for faster training etc.) 
In the evaluation, it is consistent with the benchmark, and the metrics are calculated at the point-level. So there will be some difference between the two printed results.
In the process of projection from point cloud to range image, there are some issues such as multiple points corresponding to one pixel. I guess this is also the reason why gt evaluation from point cloud is lower than that from image evaluation

**Comment by MaxChanger** [comment]
Since there is no update. I would like to close this issue.

Feel free to reopen this issue if needed.
