### ISSUE TITLE
how to get the moving labels?

### ISSUE THREAD

**Issue by beyounged** [haomo-ai/MotionSeg3D#15]
hi, I have a problem about how to get the labels only moving (not unlabeled or static)?

**Comment by MaxChanger** [comment]
Sorry, can you explain the problem further? Do you mean how to label new data? Or how to visualize data labels?

**Comment by beyounged** [comment]
作者你好，我的意思是你的labels应该是一个三分类的labels（unlabeled or static or moving）当使用.raw.yaml的时候，因为输出shape是[bs,3,64,2048] ？labels应该是给点云打上[0,1,2]的标签（即proj_labels的取值是0，1，2中之一？）那能否单独拿只有moving的labels？

**Comment by MaxChanger** [comment]
1. So proj_labels is one of 0,1,2, right?  
    Yes, This is the same as the mapping to the right of `learning_map` in yaml.
3. Can you take the moving labels separately?
    Do you mean slicing the output labels? such as `pred_label[..., 1:2, :, :]`.

If I understand wrong, please describe in more detail

**Comment by beyounged** [comment]
Hi，抱歉回复晚了，关于第二点，我想问是否可以单独将proj_labels里的动态标签[2]保留，然后其余标签（静态/unlabeled）都为[0]？换句话说，是否提供了只有动态类别的标签？如果没有，应该如何制作？

**Comment by MaxChanger** [comment]
Hello, what you are talking about should be the slicing operation in python. 
It should be OK to mask the predicted label according to the value.

**Comment by beyounged** [comment]
ok, thanks for your quick reply, I am interested in this project, it's a wonderful work!

**Comment by MaxChanger** [comment]
Thank you, I will close this issue, if you have other questions, welcome to open a new issue.
