### ISSUE TITLE
heisai lidar data process

### ISSUE THREAD

**Issue by fengluodb** [haomo-ai/MotionSeg3D#2]
May I ask how do you prepare heisai lidar data. I want to knwo how to generate poses.txt and calib.txt

**Comment by MaxChanger** [comment]
Thank you for your interest in our project. 

For any (rotated) LiDAR data, the format of pose.txt and config.txt is the same as that of KITTI. The pose can be the localization result of GNSS/RTK, the result obtained by a SLAM system, or the result obtained by performing ICP or pose-graph-optimization on a sequence. To facilitate debugging, it is recommended to convert the first frame to the world system.

calib.txt is the extrinsics of each sensor, which also conforms to the definition of KITTI. If the pose.txt is the poses under LiDAR coordinate system, Tr should be an identity matrix.

Some related info: https://github.com/PRBonn/LiDAR-MOS/issues/52#issuecomment-1174820247

**Comment by fengluodb** [comment]
Thank you very much. You answer hepl me a lot.
