### ISSUE TITLE
Do I need to generate residual images for the test sequence?

### ISSUE THREAD

**Issue by Lizhijian-123** [haomo-ai/MotionSeg3D#24]
thanks for your code.
Do i need to generate residual images for the test sequence(11-21) while i am training the model? or I just need to generate residual image for 0-10 sequences

**Comment by MaxChanger** [comment]
Yes, you need to generate the residual image of the test set

**Comment by Lizhijian-123** [comment]
> Yes, you need to generate the residual image of the test set

I only generated residual images for the 00-10 sequence, and during the training process, I found that it seems that the 11-21 sequence was not used, so it was not generated. Only train and validate (08 sequence). What impact does this have on this training?

**Comment by MaxChanger** [comment]
Hello, Seq11-21 is not used during training, it is required when offline test generates prediction label and upload it to SemanticKITTI's benchmark website.

You only need to make a simple modification to `utils/auto_gen_residual_images.py` to generate residual images of seq 11-21.

**Comment by Lizhijian-123** [comment]
> Hello, Seq11-21 is not used during training, it is required when offline test generates prediction label and upload it to SemanticKITTI's benchmark website.
> 
> You only need to make a simple modification to `utils/auto_gen_residual_images.py` to generate residual images of seq 11-21.

thanks

**Comment by Lizhijian-123** [comment]
> Hello, Seq11-21 is not used during training, it is required when offline test generates prediction label and upload it to SemanticKITTI's benchmark website.
> 
> You only need to make a simple modification to `utils/auto_gen_residual_images.py` to generate residual images of seq 11-21.

so sorry to bother,I want to know if my point cloud can be converted to ROSBAG format through kitti2bag after being processed by scan_cleaner? thanks

**Comment by MaxChanger** [comment]
@Lizhijian-123 Sorry I haven't tested this function, you can consult it in the LiDAR-MOS repo https://github.com/PRBonn/LiDAR-MOS
