### ISSUE TITLE
warnings.warn(F64_PRECISION_WARNING)

### ISSUE THREAD

**Issue by noobth1nker** [haomo-ai/MotionSeg3D#25]
When I execute visualize.mos.py, if I choose the results in oursv2 for visualization, many frames of data will appear completely black. However, if I choose the results in oursv1 for visualization, this situation will not occur. In both cases, a UserWarning will appear: GPUs can't support floating point data with more than 32 bits, precision will be lost due to downcasting to 32 bit float. I don't know if it's the issue with this warning prompt, I couldn't find a solution online.
![9d2b1afbeb55e4deb7de017519e9d2da](https://github.com/haomo-ai/MotionSeg3D/assets/69454768/a7021cc5-c7ad-480f-8857-9a927850fa93)
![b4ac762e159237723c3b345b2353d4d2](https://github.com/haomo-ai/MotionSeg3D/assets/69454768/bed2acb4-cf16-4812-8c8e-d839c09d7af7)

**Comment by MaxChanger** [comment]
Hi, could you provide information about your running environment, GPU version, cuda version, and pytorch version?
This looks more like some kind of problem with GPU or CUDA.

**Comment by MaxChanger** [comment]
I found some solutions that may be helpful to you. https://github.com/napari/napari/issues/3726
It seems that the underlying package vispy that the visualization tool depends on reported this error to you?

Below is the warning mentioned in this issue. Not sure if it's similar to yours. If so, maybe you can adjust the vispy version?
> /home/czaki/.pyenv/versions/napari/lib/python3.8/site-packages/vispy/gloo/texture.py:28: UserWarning: GPUs can't support floating point data with more than 32-bits, precision will be lost due to downcasting to 32-bit float.!

**Comment by noobth1nker** [comment]
I'm sorry for the delayed response. I tried updating the version of Vispy from Vispy0.7.0 to Vispy0.11.0, but it still doesn't work. My GPU version is the 1050Ti laptop version, cuda version is 12.2, pytorch version is 1.7.0, and the versions of other packages are consistent with the versions in your environment.yaml and requirements. txt files.
![73be5c6a278c5d25bad99adbf01aa720](https://github.com/haomo-ai/MotionSeg3D/assets/69454768/f0fae68e-5c29-4ad1-96b8-7dc68b379d10)

**Comment by MaxChanger** [comment]
Sorry, I don't have a similar environment to reproduce your problem, so it's difficult to provide helpful advice. It feels like there is an environmental problem such as the package used or cuda, etc., which can be investigated from this perspective.
If you have any questions about the algorithm of our project, please feel free to discuss it.

**Comment by noobth1nker** [comment]
Thank you for your reply. I will try changing the environment and give it a try.

**Comment by noobth1nker** [comment]
作者您好，我最近使用别的主机进行测试，发现还是会出现我上面提到的问题，我详细检查了一下输出结果的具体数据，使用预训练模型并使用python infer.py -d ./toydata -m ./log/motionseg3d_pointrefine -l ./pred/oursv2 -s valid --pointrefine这个指令输出的结果中，无法可视化显示的帧的.label文件数据全为0（见附图）。因此我觉得是模型输出的问题导致我之前出现的情况，请问这个该怎么解决呢？
![QQ图片20240509125411](https://github.com/haomo-ai/MotionSeg3D/assets/69454768/783ea3b7-a056-493d-96d2-f219c2f71cf7)
