### ISSUE TITLE
预训练模型输出结果错误

### ISSUE THREAD

**Issue by noobth1nker** [haomo-ai/MotionSeg3D#26]
作者您好，我最近使用别的主机进行测试，发现还是会出现#25中的问题，我详细检查了一下输出结果的具体数据，使用预训练模型并使用python infer.py -d ./toydata -m ./log/motionseg3d_pointrefine -l ./pred/oursv2 -s valid --pointrefine这个指令输出的结果中，无法可视化显示的帧的.label文件数据全为0（见附图）。因此我觉得是模型输出的问题导致我之前出现的情况，请问这个该怎么解决呢？
![QQ图片20240509125411](https://github.com/haomo-ai/MotionSeg3D/assets/69454768/02a1257f-d5cb-49bc-b039-ceda7879649f)

**Comment by MaxChanger** [comment]
您好，或许可以稍修改一下代码看一下GT label是什么样的？

**Comment by noobth1nker** [comment]
GT label是正常的，有大于250的值也有小于250的值，可以正确分辨出移动中和静止的物体
![QQ图片20240510062506](https://github.com/haomo-ai/MotionSeg3D/assets/69454768/be715772-d805-4fa0-83f0-e0a7da91afc6)

**Comment by noobth1nker** [comment]
而且用python infer.py -d ./toydata -m ./log/motionseg3d_pointrefine -l ./pred/oursv2 -s valid --pointrefine指令输出的很多帧的.label中的数据都很离谱，数值特别大，已经和learning map没有关系了
![QQ图片20240510142822](https://github.com/haomo-ai/MotionSeg3D/assets/69454768/25856798-47d6-4577-828a-51a8bb3a863d)

**Comment by MaxChanger** [comment]
<img width="720" alt="image" src="https://github.com/haomo-ai/MotionSeg3D/assets/35401968/3f7ab49c-f6b4-493d-9d94-13577bd28f80">
你好我现在没有方便可视化的机器，刚仅跑了一下infer，保存的label是没有问题的，不会出现你全0的问题，可能还是你的环境之类的问题

**Comment by MaxChanger** [comment]
另外有一个小问题可能需要注意，README中有些 [2022/09/26] Update the KITTI-Road labels [here](https://drive.google.com/file/d/131tKKhJiNeSiJpnlrXS43bHgZJHh9tug/view?usp=sharing), remap the label to 9 and 251
我看了下toydata压缩包中还是老的0, 252 但是这个不影响模型推理
<img width="740" alt="image" src="https://github.com/haomo-ai/MotionSeg3D/assets/35401968/08aceb45-bf2b-43ef-9730-4667fb482d26">
<img width="1364" alt="image" src="https://github.com/haomo-ai/MotionSeg3D/assets/35401968/aca6bf26-2668-47b4-b2d0-e8b2c5694d90">

**Comment by noobth1nker** [comment]
好的，谢谢您，我再试试更改一下环境配置

**Comment by noobth1nker** [comment]
请问您的cuda配置还是配置文件中写的 
  - python=3.7.7
  - pytorch=1.7.0
  - torchvision=0.8.0
  - cudatoolkit=11.0
 这样的吗？

**Comment by noobth1nker** [comment]
谢谢作者，我换用3070的显卡，重新将环境配置好后就没有这个问题了。但是想和您建议一下，requirements.txt里面的cuda=11.0不支持算力为86的显卡，如果想要支持算力86的显卡，cuda最低需要11.1，同时pytorch的版本也要跟着变，如果显卡算力过于低就可能出现我之前提到的问题。

**Comment by MaxChanger** [comment]
很高兴看到问题解决了，requirements.txt里面只是当时配置的一个参考，2080Ti 3090我这边测试都是正常跑的，两者的cuda版本可能也不一致，cuda的版本一直不是很严格的要求吧，一般需要你结合自身机器情况进行适配
