### ISSUE TITLE
About the annotation of KITTI-Road-MOS

### ISSUE THREAD

**Issue by consolas-K** [haomo-ai/MotionSeg3D#7]
Hello, could you tell me which annotation tool you used?

**Comment by MaxChanger** [comment]
Hi, more details could be found in https://github.com/haomo-ai/MotionSeg3D/blob/master/config/kitti_road_mos.md

> More specifically, we first use auto-mos labeling method ([link](https://arxiv.org/pdf/2201.04501.pdf)) to automatically generate the MOS labels for KITTI-Road data. We then use a point labeler ([link](https://github.com/jbehley/point_labeler)) to manually refined the labels.

**Comment by consolas-K** [comment]
Thank you for your reply
